version: "2"

linters:
  default: all

  disable:
    - canonicalheader
    - containedctx
    - contextcheck
    - cyclop
    - depguard
    - dupword
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - errname
    - exhaustruct
    - exhaustive
    - forbidigo
    - funlen
    - funcorder
    - gochecknoglobals
    - gocognit
    - godoclint
    - godot
    - godox
    - inamedparam
    - intrange
    - ireturn
    - lll
    - mnd
    - nestif
    - noinlineerr
    - nolintlint
    - paralleltest
    - recvcheck
    - tagalign
    - tagliatelle
    - testpackage
    - testifylint
    - unparam
    - varnamelen
    - wrapcheck
    - zerologlint

  settings:
    govet:
      enable:
        - fieldalignment
    gosec:
      excludes:
        - G103

    gocritic:
      disabled-checks:
        - commentFormatting
        - assignOp

    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Println
        - os.Close
        - strings.Builder.WriteString
        - (io.Closer).Close

    ireturn:
      allow:
        - error

    staticcheck:
      checks:
        - "-S1019"

    tagliatelle:
      case:
        rules:
          yaml: snake

    revive:
      enable-all-rules: true
      rules:
        # ============================
        # ERROR-FIRST RULES
        # ============================
        - name: line-length-limit
          severity: error
          arguments: [190]

        # ============================
        # ACTIVE RULES WITH ARGUMENTS
        # ============================
        - name: atomic

        - name: unhandled-error
          exclude:
            - "**/*_test.go"
          arguments:
            - fmt.Printf
            - fmt.Println
            - strings.Builder.WriteString
            - strings.Builder.WriteByte
            - io.Closer.Close
            - net/http.ResponseWriter.Write

        - name: function-length
          arguments: [0, 0]
          disabled: false
          exclude: ["_test.go"]

        - name: cognitive-complexity
          arguments: [50]

        - name: cyclomatic
          arguments: [20]

        - name: max-control-nesting
          arguments: [7]

        # ============================
        # DISABLED RULES
        # ============================
        - name: package-comments
          disabled: true

        - name: add-constant
          disabled: true

        - name: exported
          disabled: true
          arguments:
            - disableChecksOnTypes
            - disableChecksOnConstants

        - name: max-public-structs
          disabled: true

        - name: call-to-gc
          disabled: true

        - name: comment-spacings 
          disabled: true

        - name: confusing-naming
          disabled: true

        - name: deep-exit
          disabled: true

        - name: enforce-switch-style
          disabled: true

        - name: flag-parameter
          disabled: true

        - name: confusing-results
          disabled: true

        - name: unused-parameter
          disabled: true

        - name: modifies-value-receiver 
          disabled: true

  exclusions:
    generated: lax
    rules:
      - path: (.+)_test.go
        linters:
          - gosec
          - dupl
          - goconst
      - path: helpers/(.+).go
        linters:
          - gosec
          - mnd
      - path: "(.+).go"
        linters:
          - staticcheck
        text: "could remove embedded field"

formatters:
  enable:
    - gofmt
    - goimports
